//ACTIONS FOR LOGIN
export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REDIRECT = "LOGIN_REDIRECT";

//ACTIONS FOR LOGOUT
export const LOGOUT = "LOGOUT";

//ACTIONS FOR SIGNUP
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

//RANDOM ACTIONS
export const CLEAR_ERROR = "CLEAR_ERROR";

//SIDEDRAWER ACTIONS
// export const DRAWER_OPEN = "DRAWER_OPEN";
// export const DRAWER_CLOSE = "DRAWER_CLOSE";
export const DRAWER_TOGGLE = "DRAWER_TOGGLE";
export const SHOW_ERROR = "SHOW_ERROR";
export const CLOSE_MODAL = "CLOSE_MODAL";

//ACTION TYPE FOR PROCESSING PAYMENT
export const PAYMENT_PROCESSING = "PAYMENT_PROCESSING";
export const PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const REMOVE_ITEMS_FROM_STORAGE = "REMOVE_ITEMS_FROM_STORAGE";
export const GET_ITEMS_FROM_STORAGE = "GET_ITEMS_FROM_STORAGE";
export const SET_GUEST = "SET_GUEST";
export const PAYMENT_PAGE = "PAYMENT_PAGE";

//ACTION FOR PROTECTING ROUTES
export const SELECTED_VEHICLE = "SELECTED_VEHICLE";
export const PROVIDED_OPTIONS = "PROVIDED_OPTIONS";
export const NAV_CHECKOUT = "NAV_CHECKOUT";
export const RESET_ROUTES = "RESET_ROUTES";
